### ISSUE TITLE
[C-1738] Bulk edit member attributes

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#1050]
**Problem**

Currently, if you want to edit member attributes, you have to click into every profile → edit attributes → change attribute. If you want to edit several members at once, it requires a lot of time.

**Solution**

Similar to bulk adding of tags, the user should be able to bulk edit member attributes.

![Linear-hosted image](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/36c4f4c7-a7f3-4d8f-a289-4bdaf3d015ab/f50693ce-bc36-4ff6-8994-a24056f953c6)

[Source image](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/36c4f4c7-a7f3-4d8f-a289-4bdaf3d015ab/f50693ce-bc36-4ff6-8994-a24056f953c6)

* add another endpoint for bulk editing member attributes

<sub>From [SyncLinear.com](https://synclinear.com) | [C-1738](https://linear.app/crowddotdev/issue/C-1738/bulk-edit-member-attributes)</sub>

**Comment by jonathimer** [comment]
this was requested by Skip from Vaticle

**Comment by yeganathan18** [comment]
I don't think we need another endpoint for bulk editing member attributes unless we've got a specific reason. We could probably use the same endpoint since it isn't super particular about the property we send, and simply destructs the JSON to update every member with the passed item.

If we are gonna use the same endpoint then there is no much BE work needed and only FE stuff is left to support the improvement.
