### ISSUE TITLE
[C-2484] Sort members merge suggestions by confidence

### ISSUE THREAD

**Issue by nunoeufrasio** [CrowdDotDev/crowd.dev#1813]
<sub>From [SyncLinear.com](https://synclinear.com) | [C-2484](https://linear.app/crowddotdev/issue/C-2484/sort-members-merge-suggestions-by-confidence)</sub>

**Comment by keshari1arya** [comment]
@nunoeufrasio Can you please add more details to this?

**Comment by nunoeufrasio** [comment]
Hi @keshari1arya :) 
Each merge suggestion has its confidence score, this issue is about sorting all the suggestions by confidence in descending order. No additional functionality or elements added to the UI.

<img width="1046" alt="Screenshot 2023-11-06 at 09 19 49" src="https://github.com/CrowdDotDev/crowd.dev/assets/22342669/621bbcda-b583-4a59-b92a-f5d88ec8f845">

**Comment by lausuarez02** [comment]
Hey would like to give it a try if no one took it! :)

**Comment by keshari1arya** [comment]
Hey @nunoeufrasio ,
thank you for the help and the screen shot provided. 
i can see in the DB data pickup query we are sorting it by similarity. 
![image](https://github.com/CrowdDotDev/crowd.dev/assets/16665888/fada774f-852a-4425-b3fe-cff2e7186128)

can you please let me know the exact issue you want to tackle.
if possible can you please share me a login and environment so that i can also check from my end to get to the root of the issue.

**Comment by joanagmaia** [comment]
Hey @keshari1arya, sorry to get back to you so late, our Sync tool didn't work so this issue status wasn't updated.
@joanreyero already took care of this one during the week, so it's already fixed.
Nonetheless, thank you for your interest in contributing!

Regarding login and environment, you should be able to Sign up with your google account or email normally locallly
