### ISSUE TITLE
[C-791] Job title is shown twice when member belongs to multiple organizations

### ISSUE THREAD

**Issue by joanagmaia** [CrowdDotDev/crowd.dev#574]
In the members' list page, for each organization the member is associated to, the member's job title is displayed below the organization title.

The job title should only appear one time below the organizations

![Screenshot 2023-02-24 at 12.10.50.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/728d0028-1e31-42d8-9182-1f0572da1b7c/e115cb0c-77c8-4de9-b88d-c6eafe42f248)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-791](https://linear.app/crowddotdev/issue/C-791/job-title-is-shown-twice-when-member-belongs-to-multiple-organizations)</sub>

**Comment by peoray** [comment]
@joanagmaia What do you think of this? Would like to help out

**Comment by joanreyero** [comment]
Hey @peoray! This would be awesome! Let me know if I can help you in any way 😊

**Comment by peoray** [comment]
going through the app and would need help

**Comment by peoray** [comment]
Thank you @jonathimer .

**Comment by peoray** [comment]
@jonathimer having a hard time reproducing this bug, can you help?
cc @joanagmaia

**Comment by joanagmaia** [comment]
Hey @peoray, here are some steps to reproduce this issue:
- Go to Edit page of any member
- In the edit page edit both the **Job title** and the **Organization** fields
   - Add a job title to that member, let's say COO
   - Add two organizations to that member. If you don't have any organizations yet, you can create them in that field in the same form
- Update the member and now you should have the member with a job title and two organizations
- If you access the members list page and search for that member you will see something like the issue's screenshot:
   - The job title is rendered twice. Basically for each organization, you will see the job title being rendered below

Hope this helps! I've also recorded a small video with these steps if you prefer: https://www.loom.com/share/e63e71305678480ba8183e57fae8a664

Let me know if you need anything else 😄

**Comment by jonathimer** [comment]
Hey @peoray, I'd recommend connecting e.g. Hacker News with some generic keyword (e.g. "React"). This will bring real data into your workspace.

Since Hacker News won't come with organizations, you would than have to create a few organizations manually (but those functionalities will be available once you have "real" data).

**Comment by jonathimer** [comment]
Are you getting any activities in?
Is this in cloud or self-hosted?

**Comment by peoray** [comment]
Not sure what you mean by Cloud or self hosted. The only command I ran was the script cli command. Since then, I have the app running.

Strangely enough, it doesn't actually run per se, cause the cli command does it thing and ends but then the app still runs. Not sure what that means.

I have also tried to see the DB tables using Beekeeper but I can't successfully connect.

Hope that provides enough context.

**Comment by joanagmaia** [comment]
Which cli command did you use?
My advice would be to use `cli clean-start-dev` in `scripts` folder and choose the `Yes` option when the terminal prompts `Will delete all local crowd state data (docker volumes) if you have any. Are you sure?`

This script will reset all your data and trigger all services in the backend and the frontend as well. So once you have all of these containers running you should be good to go to launch the app in `localhost:8081`

Not sure if your current problem is because you are missing to run a specific service but let me know if this works for you

**Comment by joanagmaia** [comment]
To connect to the DB are you using the credentials available in `.env.dis.local`? Inside `backend`s' folder
You should have there these variables `CROWD_DB_READ_HOST`,  `CROWD_DB_WRITE_HOST`, `CROWD_DB_PORT`, `CROWD_DB_USERNAME`, `CROWD_DB_PASSWORD`, `CROWD_DB_DATABASE`

If you use these to connect to the DB you can also access `tenants` table and update `hasSampleData` attribute to `false`. This will allow you to edit data locally even if you don't connect any integration

**Comment by peoray** [comment]
@joanagmaia this is the command I ran ` ./cli clean-start-dev` as recommended by @jonathimer. 

And yes, I did all that.

For the DB instance, I got this error
`role 'postgres' does not exist`

**Comment by joanreyero** [comment]
Can you share the output of `./cli clean-start-dev`?

**Comment by peoray** [comment]
Sure. Running the command again and chose 1. It does take a long while

**Comment by peoray** [comment]
@joanreyero 
![Uploading Screen Shot 2023-04-14 at 5.41.33 PM.png…]()

**Comment by peoray** [comment]
@joanreyero 
<img width="1432" alt="Screen Shot 2023-04-14 at 5 41 33 PM" src="https://user-images.githubusercontent.com/23735423/232105899-850de24e-4d2c-4d37-8022-ec79a957f2ab.png">

**Comment by peoray** [comment]
@joanreyero Yes, I can. This was already working. I just need a way to visualize the data on the crowd-web DB (using BeeKeeper) and also know why the integration wasn't working for me as it was taking hours to connect (I had to stop it)

**Comment by peoray** [comment]
It's been a long day. So far, I have been able to connect to my docker postgres locally and can view the tables via the terminal. However, as you can imagine, it's difficult to navigate that way. For now, it works, I just need a way to connect it via a GUI like BeeKeeper or PgAdmin

**Comment by joanreyero** [comment]
Can you show me the input you send to the GUI?

**Comment by peoray** [comment]
<img width="1432" alt="Screen Shot 2023-04-15 at 11 10 11 AM" src="https://user-images.githubusercontent.com/23735423/232207617-d5478b33-c23f-4c61-bd69-fbb5675a0fcd.png">
@joanreyero

**Comment by joanreyero** [comment]
I think the host is wrong 🙂
These are my values:
<img width="403" alt="Screenshot 2023-04-15 at 12 13 27" src="https://user-images.githubusercontent.com/37874460/232208007-90132019-b7a6-4023-bb64-3d9820526fc1.png">

**Comment by peoray** [comment]
I already tried
- host: localhost
-user:  postgres
- password: example

I only tried the IP address cause from all my googling, it seems the DB was hosted on docker and I needed to connect to it but it didn't work regardless.

However, I somehow managed to get it working (woke up this morning to see that Dev.to actually integrated), so I could edit and fix the issue (thanks @jonathimer for the suggestion). But this would hinder me from doing more comprehensive bug fixes or even adding new features cause being able to view the data would be greatly helpful instead of running SQL commands :(
