### ISSUE TITLE
[C-864] Member profile: Icon + Copy are not centered for some activities

### ISSUE THREAD

**Issue by jonathimer** [CrowdDotDev/crowd.dev#627]
![Bildschirmfoto 2023-03-07 um 12.14.51.png](https://uploads.linear.app/aebec7ad-5649-4758-9bed-061f7228a879/7fdec7da-fb55-4d8a-9b4b-60282c84b71c/7af099df-0683-4452-9b7d-3aaeb8931928)

<sub>From [SyncLinear.com](https://synclinear.com) | [C-864](https://linear.app/crowddotdev/issue/C-864/member-profile-icon-copy-are-not-centered-for-some-activities)</sub>

**Comment by yeganathan18** [comment]
@jonathimer is there any particular user profile or screen resolution? 

Because I checked with some and couldn't reproduce 👀

**Comment by jonathimer** [comment]
hmm also can't reproduce it anymore

might have been fixed 👀

**Comment by yeganathan18** [comment]
Okay got it! Let me check locally

**Comment by yeganathan18** [comment]
Hey @jonathimer I just found the issue, and it looks the problem is with the `activity sentiment icon`

The icon `font-size is 1rem` and it takes certain height for the size, which indeed makes it look aligned. When we remove 
the icon, height that it was contributing, is also removed. Hence, the issue is caused.

Check the below screen record for more context,

https://user-images.githubusercontent.com/63534555/235488131-98d4b910-8042-41fd-880b-2cd3017d77d4.mov

### Possible Fix

Right now, the `activity message` font size is `14px` and we can either, 

1) increase the activity message text size to `1rem` 

<img width="556" alt="image" src="https://user-images.githubusercontent.com/63534555/235493031-cd83e753-e228-4adf-a2e8-6b508256e5d9.png">

or

2) reduce icon font-size to 14px and add a bit of margin, like `mt-0.5`

<img width="569" alt="image" src="https://user-images.githubusercontent.com/63534555/235493008-3af926ef-6f9f-4db4-8dfe-75cbdc99454e.png">


I'm going with (2) since that looks better with overall UI and reducing the icon size from `1rem` to `14px` doesn't look like a big difference.

P.S. I wasn't able to reproduce in the local with dump data though, so used my project account in the (GitWonk) production for debugging 😛 Also sorry for getting back late, last week was kinda intense.

**Comment by jonathimer** [comment]
Hey, Thanks for picking this up!

I'm looping in our product designer @nunoeufrasio. :-)

**Comment by nunoeufrasio** [comment]
Hey @yeganathan18 thanks for the fix! Option 2 is the best indeed 👌

**Comment by yeganathan18** [comment]
Let's go! 👻
