### ISSUE TITLE
[C-919] Filter by lastEnriched in the frontend

### ISSUE THREAD

**Issue by joanreyero** [CrowdDotDev/crowd.dev#655]
From a user:

*I wanted to find all profiles I did not enrich yet, but such a filter does not exist on the members list page. Am I missing it?*

This is ready in the backend.

<sub>From [SyncLinear.com](https://synclinear.com) | [C-919](https://linear.app/crowddotdev/issue/C-919/filter-by-lastenriched-in-the-frontend)</sub>

**Comment by joanreyero** [comment]
Last enriched is a date

**Comment by joanreyero** [comment]
But we could filter by lastEnriched not being NULL, no?

**Comment by joanreyero** [comment]
This would give us the boolean 😄

**Comment by joanagmaia** [comment]
Yeah for sure, it would work as a boolean. I think the biggest doubt is how we can display it in the UI. The design Nuno shared is what the frontend uses for Boolean fields.

If we want to use that design for `lastEnriched` then we need to hard-code the logic behind this particular filter so that the payload goes with the correct type and value to the backend

@joanreyero what was your suggestion to display it in the UI?

**Comment by joanreyero** [comment]
I'm not sure I understand you.

Why can't we keep Nuno's design, and then the filters are:

```
lastEnriched: {
  null
}
```

or

```
lastEnriched: {
  not: {
    null
  }
}
```

I think this should work, no? Or am I misunderstanding something?

**Comment by joanagmaia** [comment]
I was just trying to understand if you had any other suggestion but maybe I just misunderstood your message before.

But yes, we can use that and Nuno's designs 👍
