### ISSUE TITLE
Is root access required?

### ISSUE THREAD

**Issue by rodrigorivera** [CrowdDotDev/crowd.dev#67]
### What problem are you trying to solve?

I cloned the main repository directly after failing to fork. I execute 
`bash start.sh` and the output is

`Trying to install ssl tools, need to get sudo privileges
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?`

I do not want to execute this as root. I wish it runs exclusively as a docker image without installing anything on my system. Also, you are asking too much to execute something under sudo that I have not yet fully understood. But let us assume that I trust you and execute it.

```
fatal: unsafe repository ('/mnt/c/repositories/crowddev/crowd.dev' is owned by someone else)
To add an exception for this directory, call:

        git config --global --add safe.directory /mnt/c/repositories/crowddev/crowd.dev
```

### What's your suggested solution?

I want that everything is self-contained, and the only requirements for my host system should docker and nothing else.

**Comment by joanreyero** [comment]
Thanks for raising this issue! 🙏🏼

We need to execute it as root because we need to provide SSL certificates so we can run on `HTTPS`. This is because the Slack integration requires it for the OAuth flow. We are looking into finding a solution for this. Therefore, as far as we know, we cannot provide a local Slack integration without SSL.

We are aware that this solution is not good either. We are looking into what we can do to fix this issue.
