### ISSUE TITLE
[C-1427] Ignoring 'unstar' activity

### ISSUE THREAD

**Issue by RaginiAngarka** [CrowdDotDev/crowd.dev#858]
### crowd.dev edition

Cloud (hosted)

### Version

Frontend - 0.5.0

### What happened?

Issue : If user has starred, unstarred and again star the repo. It is counting every star activity.
Steps:-
Star the repo
Remove star from the repo using same github id
Again star the repo
Actual result:
It is counting all the activities star and unstar activities. 

Refer to: https://github.com/communitybridge/easycla/pulls
Expected Result: Star count should match with original source.

<img width="1431" alt="Screenshot 2023-05-12 at 7 20 29 PM" src="https://github.com/CrowdDotDev/crowd.dev/assets/87848481/13e667b2-a1a2-4bb7-80d3-cb60c5deb6a0">
<img width="1432" alt="Screenshot 2023-05-12 at 7 24 33 PM" 

<img width="1432" alt="Screenshot 2023-05-12 at 7 24 33 PM" src="https://github.com/CrowdDotDev/crowd.dev/assets/87848481/3e89e568-6d54-41bb-8c12-fc80cae53142">

It means it is only counting the number of activities. If user is removing star, it is not accounting that activity. 
It is ignoring 'unstar' activity.

<sub>[C-1427](https://linear.app/crowddotdev/issue/C-1427/ignoring-unstar-activity)</sub>

**Comment by joanreyero** [comment]
Hey @RaginiAngarka. 

This was caused because we were missing to track `unstar` activities. This has now been fixed. The expected behaviour is that we track both the starring and unstarring of repos. Therefore, you might see more than one star per member per repo. The problem here is that we were failing to fetch the unstar in the middle.
