### ISSUE TITLE
Integration issue in dev mode - provider key error

### ISSUE THREAD

**Issue by Dhruwang** [CrowdDotDev/crowd.dev#942]
### crowd.dev edition

Community (self hosted)

### Version

v0.33.0

### What happened?

On Integrations page

Cant connect any of the available platforms

https://github.com/CrowdDotDev/crowd.dev/assets/67850763/8a65c63d-4060-434f-a96e-d5fc33c8de96

## Error in console
![Screenshot from 2023-06-03 22-11-38](https://github.com/CrowdDotDev/crowd.dev/assets/67850763/3d492639-fff0-41c7-80a4-ab8aa09cbc38)

**Comment by Charlotte0709** [comment]
Hi @Dhruwang, thanks for raising this! We will check this out ASAP and get back to you.

**Comment by joanreyero** [comment]
Hey @Dhruwang! Thanks for raising this

To connect integrations in development mode, you must first create and configure an app. You can find the docs [here](https://docs.crowd.dev/docs/self-hosting). The reason is that we cannot expose our app secrets to the community. 

However, some integrations can be connected without having to do any configuration, such as HackerNews.

**Comment by Dhruwang** [comment]
Ok got it , Thank you !
